name: Generate Snake Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  # Allows you to run this job manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: Tejas-I-M
          
          # These are the files that will be generated
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Pushes the generated images to a branch called 'output'
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
